### ISSUE TITLE
[bug] The requested module '@lix-js/client' does not provide an export named 'findRepoRoot'

### ISSUE THREAD

**Issue by NunciosChums** [opral/monorepo#2042]
### Problem

```shell
npm run build

> build-test@0.0.1 build
> paraglide-js compile --project ./project.inlang && vite build

ℹ [paraglide] Compiling inlang project at "./project.inlang".

 WARN  Could not find repository root for path /Users/mac/projects/svelte/build-test/project.inlang

ℹ [paraglide] Sucessfully compiled the project.
failed to load config from /Users/mac/projects/svelte/build-test/vite.config.js
error during build:
file:///Users/mac/projects/svelte/build-test/node_modules/@inlang/paraglide-js-adapter-unplugin/dist/index.js:3
import { openRepository, findRepoRoot } from "@lix-js/client";
                         ^^^^^^^^^^^^
SyntaxError: The requested module '@lix-js/client' does not provide an export named 'findRepoRoot'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadConfigFromBundledFile (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68380:21)
    at async loadConfigFromFile (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68237:28)
    at async resolveConfig (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67838:28)
    at async build (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67010:20)
    at async CAC.<anonymous> (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/cli.js:845:9)
```

### Reproduction

1. npm create svelte@latest build-test
```shell
Need to install the following packages:
create-svelte@6.0.8
Ok to proceed? (y) y

create-svelte version 6.0.8

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  Yes, using JavaScript with JSDoc comments
│
◇  Select additional options (use arrow keys/space bar)
│  Add ESLint for code linting, Add Prettier for code formatting
│
└  Your project is ready!

✔ Type-checked JavaScript
  https://www.typescriptlang.org/tsconfig#checkJs

✔ ESLint
  https://github.com/sveltejs/eslint-plugin-svelte

✔ Prettier
  https://prettier.io/docs/en/options.html
  https://github.com/sveltejs/prettier-plugin-svelte#options
```

2. cd build-test
3. package.json
```json
{
  "name": "build-test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "paraglide-js compile --project ./project.inlang && vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
    "lint": "prettier --check . && eslint .",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "@inlang/paraglide-js": "1.2.1",
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.3.3",
    "@sveltejs/vite-plugin-svelte": "^3.0.1",
    "@types/eslint": "8.56.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-svelte": "^2.35.1",
    "prettier": "^3.2.2",
    "prettier-plugin-svelte": "^3.1.2",
    "svelte": "^4.2.8",
    "svelte-check": "^3.6.3",
    "typescript": "^5.3.3",
    "vite": "^5.0.11"
  },
  "dependencies": {
    "@inlang/paraglide-js-adapter-vite": "^1.2.3"
  },
  "type": "module"
}
```
4. vite.config.js
```js
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";
import { paraglide } from "@inlang/paraglide-js-adapter-vite";
import path from "path";

export default defineConfig({
  plugins: [
    sveltekit(),
    paraglide({
      project: "./project.inlang",
      outdir: "./src/paraglide"
    })
  ],
  resolve: {
    alias: {
      // This is the alias you can use in your code
      // you can change it to whatever you want
      $paraglide: path.resolve(__dirname, "./src/paraglide")
    }
  }
});
```
5. project.inlang/settings.json
```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "ko",
  "languageTags": ["ko", "zh-cn", "zh-tw", "en"],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
  ],
  "plugin.inlang.messageFormat": {
    "pathPattern": "./messages/{languageTag}.json"
  }
}
```
6. npm install
7. npm run build
```shell
> build-test@0.0.1 build
> paraglide-js compile --project ./project.inlang && vite build

ℹ [paraglide] Compiling inlang project at "./project.inlang".

 WARN  Could not find repository root for path /Users/mac/projects/svelte/build-test/project.inlang

ℹ [paraglide] Sucessfully compiled the project.
failed to load config from /Users/mac/projects/svelte/build-test/vite.config.js
error during build:
file:///Users/mac/projects/svelte/build-test/node_modules/@inlang/paraglide-js-adapter-unplugin/dist/index.js:3
import { openRepository, findRepoRoot } from "@lix-js/client";
                         ^^^^^^^^^^^^
SyntaxError: The requested module '@lix-js/client' does not provide an export named 'findRepoRoot'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadConfigFromBundledFile (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68380:21)
    at async loadConfigFromFile (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:68237:28)
    at async resolveConfig (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67838:28)
    at async build (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67010:20)
    at async CAC.<anonymous> (file:///Users/mac/projects/svelte/build-test/node_modules/vite/dist/node/cli.js:845:9)
```

### Other information

- OS: macOS Sonoma 14.2.1

**Comment by samuelstroschein** [comment]
@janfjohannes I think this happends because you don't use changeset. Changes in lix are not deployed to NPM but used in deployed libs that use the lix client

**Comment by bayaderpack** [comment]
Same issue and dont know how to fix it

**Comment by LorisSigrist** [comment]
@janfjohannes I can hotfix this for now by bundling lix into paraglide, but that's not a great long-term solution. Regularly deploying lix will be necessary going forward

**Comment by LorisSigrist** [comment]
@janfjohannes I can hotfix this for now by bundling lix into the vite adapter, but that really shouldn't be necessary. `@lix-js/client` should be available as an up-to-date package on npm. All our apps depend on it. If it's not available we are forced to bundle everything, greatly increasing both package-size and effort.

**Comment by LorisSigrist** [comment]
This has been fixed in `@inlang/paraglide-js-adapter-vite@1.2.4`. Please update and try again

**Comment by janfjohannes** [comment]
@samuelstroschein  @LorisSigrist   ahh  i see, sorry for this.   if it behaves this way i am surprised we did not have many more issues like this.

**Comment by samuelstroschein** [comment]
@janfjohannes was the issue a missing changeset or a bug in changeset (that did not trigger an update in paraglide)?

**Comment by janfjohannes** [comment]
@samuelstroschein  no bug in changeset,  i just did not always add a changeset when lix changes, only when i wanted to make a realse. but as dependencies are locally using whatever is in the repo this lead to the bug. will always do the changeset from now on and investigate automating this if we dont switch to rush or something else.
