### ISSUE TITLE
[bug] Cannot run `npx @inlang/cli machine translate`

### ISSUE THREAD

**Issue by buhodev** [opral/monorepo#2239]
### Problem

Machine translations failed

<img width="620" alt="image" src="https://github.com/opral/monorepo/assets/105121122/9975b437-23d9-4195-96de-0962053a952d">

### Expected behavior

CLI should translate missing IDs

### Reproduction

1. run `npx @inlang/cli machine translate --force --project ./project.inlang`
2. see error

**Comment by felixhaeberle** [comment]
@samuelstroschein Can this be related to the change of `languageTag` from normal devDependency to dependency in https://github.com/opral/monorepo/pull/2208 ? 

I could not reproduce the error locally by running the dev server alongside the cli for the rpc call to work but I get the error when only running build for the CLI & then executing locally.

**Comment by felixhaeberle** [comment]
@buhodev Can you please make sure to run the latest CLI version?

```sh
npx @inlang/cli@latest machine translate --force --project ./project.inlang
```

**Comment by felixhaeberle** [comment]
Added more prominent `@latest` infromation in Troubleshoot section in Docs
https://github.com/opral/monorepo/commit/b02466242aa33fed444f84ba644039b44766ecdc

**Comment by buhodev** [comment]
@felixhaeberle Sure thing. I did it and still the error persists:

<img width="660" alt="image" src="https://github.com/opral/monorepo/assets/105121122/760a9ead-38b1-437b-968e-15c5ded74658">

**Comment by felixhaeberle** [comment]
@buhodev Any special characters in the message where it fails? Or in the messages in general?

**Comment by buhodev** [comment]
Nope, it's only when there are more than 10 messages (with 10 messages they translate but still get the error). GMT -4. Alright

**Comment by felixhaeberle** [comment]
Summary of call with @buhodev: JSON is looking fine, fetch fails randomly on messages.
@buhodev Could possibly share the JSON (10 message) content which fails for you for us to further investigate?

**Comment by buhodev** [comment]
```json
{
	"$schema": "https://inlang.com/schema/inlang-message-format",
	"error_400": "Sorry, we could not process your request",
	"error_401": "You need to login to access this page",
	"error_403": "Sorry, you're not allowed to access this page",
	"error_404": "Sorry, we couldn't find this page",
	"error_529": "Sorry, you have made too many requests. Try again in 1 minute",
	"error_500": "Sorry, something went wrong on our side. Please refresh the page or try again later",
	"go_home": "Go home",
	"banner_dismiss": "Dismiss",
	"scroll_to_top_label": "Scroll to top",
	"header_skip_link": "Skip to main content"
}
```

**Comment by felixhaeberle** [comment]
I just tested with this `settings.json` inside of `project.inlang` directory:

```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": [
		"en",
		"de"
	],
	"modules": [
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js"
	],
	"plugin.inlang.messageFormat": {
		"pathPattern": "./messages/{languageTag}.json"
	}
}
```

and this `en.json` file:

```json
{
	"$schema": "https://inlang.com/schema/inlang-message-format",
	"error_400": "Sorry, we could not process your request",
	"error_401": "You need to login to access this page",
	"error_403": "Sorry, you're not allowed to access this page",
	"error_404": "Sorry, we couldn't find this page",
	"error_529": "Sorry, you have made too many requests. Try again in 1 minute",
	"error_500": "Sorry, something went wrong on our side. Please refresh the page or try again later",
	"go_home": "Go home",
	"banner_dismiss": "Dismiss",
	"scroll_to_top_label": "Scroll to top",
	"header_skip_link": "Skip to main content"
}
```

which works for me:

```sh
felixhaberle@MBP-von-Felix ~/D/g/m/i/s/p/p/example-app (main)> npx @inlang/cli@latest  machine translate --force --project ./project.inlang
ℹ Machine translated message "error_400"                                                                                                    3:45:44 PM
ℹ Machine translated message "scroll_to_top_label"                                                                                          3:45:44 PM
ℹ Machine translated message "error_404"                                                                                                    3:45:44 PM
ℹ Machine translated message "banner_dismiss"                                                                                               3:45:44 PM
ℹ Machine translated message "error_403"                                                                                                    3:45:44 PM
ℹ Machine translated message "go_home"                                                                                                      3:45:44 PM
ℹ Machine translated message "header_skip_link"                                                                                             3:45:44 PM
ℹ Machine translated message "error_500"                                                                                                    3:45:44 PM
ℹ Machine translated message "error_401"                                                                                                    3:45:44 PM
ℹ Machine translated message "error_529"                                                                                                    3:45:44 PM
✔ Machine translate complete.                                                                                                               3:45:52 PM
felixhaberle@MBP-von-Felix ~/D/g/m/i/s/p/p/example-app (main)> npx @inlang/cli@latest machine translate --force --project ./project.inlang
✔ Machine translate complete.   
```

The `de.json` gets automatically created with the translations.
@buhodev Are you running with some VPN or behind some special wifi setup?
And, can you make sure to have the latest cli installed in your dependency package.json aswell, I recognized if you have an old version (v1) there, @latest will not work as expected.

**Comment by buhodev** [comment]
I don't have the CLI installed in my package.json. This is my settings.json

```json
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de"],
	"modules": [
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
	],
	"plugin.inlang.messageFormat": {
		"pathPattern": "./resources/{languageTag}.json"
	}
}
```

Let me install the CLI and test again.

**Comment by buhodev** [comment]
I was not using a VPN or had weird WiFi settings. After installing the latest @inlang/cli, now I get a more interesting error:

```sh
> npx @inlang/cli@latest machine translate --force --project ./project.inlang && vite build


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@lates:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dis:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@lates:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js": 5:14:51 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


[5:14:51 AM]  ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index:

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  No plugin provides a loadMessages() or saveMessages() function                                                5:14:51 AM

In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the.

  
  In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to t.
  at resolvePlugins (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:94988:24)
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95063:33)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ELIFECYCLE  Command failed with exit code 1.

frontend on  buho/add-components [✘!+?] via 🍞 v1.0.26 via  v20.11.1 took 3m12s 
❯ pnpm build

> syself-frontend@0.0.1 build /home/buhodev/syself/frontend
> npx @inlang/cli@latest machine translate --force --project ./project.inlang && vite build


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js":                             5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js":                         5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js":                       5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js":                            5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js":                       5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js":                                       5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js":                                   5:20:28 AM

TypeError: fetch failed

  
  TypeError: fetch failed
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95022:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  No plugin provides a loadMessages() or saveMessages() function                                                                                      5:20:28 AM

In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins htt.

  
  In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins h.
  at resolvePlugins (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:94988:24)
  at resolveModules (/home/buhodev/.npm/_npx/f0d5f4a79cb68f25/node_modules/@inlang/cli/dist/main.js:95063:33)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by felixhaeberle** [comment]
@jldec This sounds like a potential sdk error regarding fetch in the module resolution.

**Comment by samuelstroschein** [comment]
@felixhaeberle dev or normal dependency is irrelevant for the cli. everything is bundled. 

@buhodev what node version is used? 

i suspect a the RPC server which forwards the request to google to be flacky

**Comment by jldec** [comment]
I've been working with the machine translate cli today and this error is happening randomly in my setup.
I thought it was the volume of messages because I'm trying test a larger set of message (hence no issue filed yet) 
My suspecion is that there is rate limiting - sometimes I can translate 100 messages, and then 0. 
I'll try to instrument the proxy to see why the fetches are failing.

**Comment by buhodev** [comment]
> @buhodev what node version is used?

Node v20.11.1 and Bun 1.0.26 both fail on my end. Same if I reroute the traffic using a VPN

**Comment by jldec** [comment]
I debugged this today - The root cause of this error apper to be too many concurrent rpcs (fetch requests).

Projects with more messages generate correspondingly more rpcs, because we send a request per message, irrespective of whether it needs to be translated or not. 

I will push a quick CLI PR to limit concurrent requests, and we can follow up with an issue to skip rpcs for messages that don't need translation.

**Comment by felixhaeberle** [comment]
@jldec Thanks Jürgen, great insight!🙏

**Comment by buhodev** [comment]
> I will push a quick CLI PR to limit concurrent requests, and we can follow up with an issue to skip rpcs for messages that don't need translation.

If I remember correctly, before it didn't translate messages already translated (because I remember changing the content of a message in English, running translate and then the message in German stayed the same). Now it seems to translate everything regarding the message is already translated or not

**Comment by felixhaeberle** [comment]
was probably accidentally removed with speed improvements/ concurrent optimization by @samuelstroschein — I can't remember any other change "lately".

**Comment by felixhaeberle** [comment]
@buhodev Can you check if it works now with the newly released version?

**Comment by buhodev** [comment]
It's working now! 🎉
